services:
  postgres:
    image: postgres:17-alpine
    container_name: coffee-postgres
    environment:
      POSTGRES_DB: coffee_platform
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_password
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - coffee-network

  redis:
    image: redis:7-alpine
    container_name: coffee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coffee-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  coffee-network:
    driver: bridge